#!/bin/bash

red='\x1b[31;1m'
yellow='\x1b[33;1m'
green='\x1b[32;1m'
plain='\033[0m'
magenta='\e[95m'
cyan='\e[96m'   
none='\e[0m' 

# $1: instance name, $2: machine type, $3: zone, $4: firewall rule name, $5: username, $6: password, $7: message, $8: token
# if [[ -n $1 ]] && [[ $2 == e2-* ]] && [[ -n $3 ]] && [[ -n $4 ]] && [[ -n $8 ]] && [[ $(($(date +%s) - $8)) -lt 120 ]] && [[ $(($(date +%s) - $8)) -ge 0 ]]; then
#if [[ -n cluster-404-m ]] && [[ $2 == e2-standard-4 ]] && [[ -n asia-southeast1-b ]] && [[ -n firewall ]] && [[ -n 404 ]] && [[ $(($(date +%s) - 404)) -lt 120 ]] && [[ $(($(date +%s) - 404)) -ge 0 ]]; then

#echo -e "${green}Creating auth list ...${plain}"
#gcloud auth list

#echo -e "${green}Creating config list project ...${plain}"
#gcloud config list project

#echo -e "${green}Creating git clone ...${plain}"
#git clone https://github.com/googlecodelabs/orchestrate-with-kubernetes.git

#echo -e "${green}Creating Region ...${plain}"
#gcloud config set compute/zone asia-southeast1-b

##!/bin/bash

#red='\x1b[31;1m'
#yellow='\x1b[33;1m'
#green='\x1b[32;1m'
#plain='\033[0m'
#magenta='\e[95m'
#cyan='\e[96m'   
#none='\e[0m' 

# $1: instance name, $2: machine type, $3: zone, $4: firewall rule name, $5: username, $6: password, $7: message, $8: token
# if [[ -n $1 ]] && [[ $2 == e2-* ]] && [[ -n $3 ]] && [[ -n $4 ]] && [[ -n $8 ]] && [[ $(($(date +%s) - $8)) -lt 120 ]] && [[ $(($(date +%s) - $8)) -ge 0 ]]; then
#if [[ -n cluster-404-m ]] && [[ $2 == e2-standard-4 ]] && [[ -n asia-southeast1-b ]] && [[ -n firewall ]] && [[ -n 404 ]] && [[ $(($(date +%s) - 404)) -lt 120 ]] && [[ $(($(date +%s) - 404)) -ge 0 ]]; then

echo -e "${cyan}Creating instance ...${plain}"
instance=$(gcloud dataproc clusters create hein-201a --region asia-southeast1 --zone asia-southeast1-b --single-node --master-machine-type e2-standard-4 --master-boot-disk-size 500 --image-version 2.0-ubuntu18)
echo -e "${cyan}Instance created.${plain}"
echo -e "${cyan}Checking firewall rule ...${plain}"
if [[ $(gcloud compute firewall-rules list --format='value(allowed)') == *"'all'"* ]]; then
echo -e "${cyan}Firewall rule already exist.${plain}"
else
echo -e "${cyan}Creating firewall rule ...${plain}"
gcloud compute firewall-rules create firewall --direction=INGRESS --priority=1000 --network=default --action=ALLOW --rules=all --source-ranges=0.0.0.0/0 --no-user-output-enabled
echo -e "${red}Firewall rule created.${plain}"
fi

#$(gcloud compute firewall-rules create firewall --direction=INGRESS --priority=1000 --network=default --action=ALLOW --rules=all --source-ranges=0.0.0.0/0) 
#$(gcloud dataproc clusters create hein-201a --region asia-southeast1 --zone asia-southeast1-b --single-node --master-machine-type e2-standard-4 --master-boot-disk-size 500 --image-version 2.0-ubuntu18)

echo -e "\n${magenta}GCP SINGAPORE SERVER 🇸🇬 ${plain}\n"

#echo -e "Username: ${green}nkka404${plain}, Password: ${green}nkka404${plain}, SSH Host :  ${green}$(grep -oP '(?<=EXTERNAL_IP: ).*' <<<"$instance")${plain}"
#echo -e "SSH Host :  ${green}$(grep -oP '(?<=EXTERNAL_IP: ).*' <<<"$instance")${plain}"echo ""


echo -e "${red}▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ ${plain}"
  echo -e "${GREEN}              Hcm Channel                 ${plain}"
echo -e "${red}▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ ${plain}"
echo ""


  echo -e "${yellow}[-] ═──────────────────⪧◇⪦─────────────────═ [-]                        ${plain}"
  echo -e "${GREEN}                                                                          ${plain}"
  echo -e "${GREEN}                 instance - 1 VM                                          ${plain}"
  echo -e "${GREEN}                 Firewall - 1 Fw                                          ${plain}"
  echo -e "${GREEN}                 vm - done                                                ${plain}"
  echo -e "${GREEN}                 vm - done                                                ${plain}"
  echo -e "${GREEN}                                                                          ${plain}"
  echo -e "${green}  ࿂  ═──⪧ Now the thing is ready to use ⪦──═                             ${plain}"
  echo -e "${GREEN}                                                                          ${plain}"
  echo -e "${yellow}[-] ═──────────────────⪧◇⪦─────────────────═ [-]                        ${plain}"

#else
#  echo -e "${red} " instance  ═──⪧  Firewall  ࿂  Done
#fi
