#!/bin/bash

red='\x1b[31;1m'
yellow='\x1b[33;1m'
green='\x1b[32;1m'
plain='\033[0m'

# $1: instance name, $2: machine type, $3: zone, $4: firewall rule name, $5: username, $6: password, $7: message, $8: token
# if [[ -n $1 ]] && [[ $2 == e2-* ]] && [[ -n $3 ]] && [[ -n $4 ]] && [[ -n $8 ]] && [[ $(($(date +%s) - $8)) -lt 120 ]] && [[ $(($(date +%s) - $8)) -ge 0 ]]; then
#if [[ -n cluster-404-m ]] && [[ $2 == e2-standard-4 ]] && [[ -n asia-southeast1-b ]] && [[ -n firewall ]] && [[ -n 404 ]] && [[ $(($(date +%s) - 404)) -lt 120 ]] && [[ $(($(date +%s) - 404)) -ge 0 ]]; then

#echo -e "${yellow}Creating auth list ...${plain}"
#gcloud auth list

#echo -e "${yellow}Creating config list project ...${plain}"
#gcloud config list project

#echo -e "${yellow}Creating git clone ...${plain}"
#git clone https://github.com/googlecodelabs/orchestrate-with-kubernetes.git

#echo -e "${yellow}Creating Region ...${plain}"
#gcloud config set compute/zone asia-southeast1-b

##!/bin/bash

#red='\x1b[31;1m'
#yellow='\x1b[33;1m'
#green='\x1b[32;1m'
#plain='\033[0m'

# $1: instance name, $2: machine type, $3: zone, $4: firewall rule name, $5: username, $6: password, $7: message, $8: token
# if [[ -n $1 ]] && [[ $2 == e2-* ]] && [[ -n $3 ]] && [[ -n $4 ]] && [[ -n $8 ]] && [[ $(($(date +%s) - $8)) -lt 120 ]] && [[ $(($(date +%s) - $8)) -ge 0 ]]; then
#if [[ -n cluster-404-m ]] && [[ $2 == e2-standard-4 ]] && [[ -n asia-southeast1-b ]] && [[ -n firewall ]] && [[ -n 404 ]] && [[ $(($(date +%s) - 404)) -lt 120 ]] && [[ $(($(date +%s) - 404)) -ge 0 ]]; then

echo -e "${yellow}Creating instance ...${plain}"
instance=$(gcloud dataproc clusters create instance-1region asia-southeast1 --zone asia-southeast1-b --single-node --master-machine-type e2-standard-4 --master-boot-disk-size 500 --image-version 2.0-ubuntu18)
echo -e "${green}Instance created.${plain}"
echo -e "${yellow}Checking firewall rule ...${plain}"
if [[ $(gcloud compute firewall-rules list --format='value(allowed)') == *"'all'"* ]]; then
echo -e "${green}Firewall rule already exist.${plain}"
else
echo -e "${yellow}Creating firewall rule ...${plain}"
gcloud compute firewall-rules create firewall --direction=INGRESS --priority=1000 --network=default --action=ALLOW --rules=all --source-ranges=0.0.0.0/0 --no-user-output-enabled
echo -e "${green}Firewall rule created.${plain}"
fi

#$(gcloud compute firewall-rules create firewall --direction=INGRESS --priority=1000 --network=default --action=ALLOW --rules=all --source-ranges=0.0.0.0/0) 
#$(gcloud dataproc clusters create instance-1region asia-southeast1 --zone asia-southeast1-b --single-node --master-machine-type e2-standard-4 --master-boot-disk-size 500 --image-version 2.0-ubuntu18)
echo -e "\n${red}GCP SINGAPORE SERVER 🇸🇬 ${plain}\n"



  echo -e "${yellow}[-] ═──────────────────⪧◇⪦─────────────────═ [-]                        ${plain}"
  echo -e "${GREEN}                                                                          ${plain}"
  echo -e "${GREEN}                 instance - 1 VM                                          ${plain}"
  echo -e "${GREEN}                 Firewall - 1 Fw                                          ${plain}"
  echo -e "${GREEN}                 vm - done                                                ${plain}"
  echo -e "${GREEN}                 vm - done                                                ${plain}"
  echo -e "${green}࿂ ═────⪧.  Now the thing is ready to use.  ⪦────═                        ${plain}"
  echo -e "${GREEN}                                                                          ${plain}"
  echo -e "${yellow}[-] ═──────────────────⪧◇⪦─────────────────═ [-]                        ${plain}"

#else
#  echo -e "${red}Token is invalid or expired. Contact the developer https://t.me/nkka404 for more information.${plain}"
#fi
